# Generated by Django 3.1.4 on 2020-12-24 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resFood', '0002_foodattribute_foodcategory_fooditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='foodChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, unique=True)),
                ('attribute', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='attribute',
        ),
        migrations.DeleteModel(
            name='foodAttribute',
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resFood.foodchoice'),
        ),
        migrations.DeleteModel(
            name='foodCategory',
        ),
    ]
