# Generated by Django 3.1.4 on 2020-12-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resFood', '0005_auto_20201225_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
